/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Subject { 'id' : bigint, 'name' : string }
export interface Topic {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'keyPoints' : Array<string>,
  'subjectId' : bigint,
  'category' : string,
}
export interface _SERVICE {
  'addSubject' : ActorMethod<[bigint, string], undefined>,
  'addTopic' : ActorMethod<
    [bigint, bigint, string, string, Array<string>, string],
    undefined
  >,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getTopic' : ActorMethod<[bigint], Topic>,
  'getTopicsBySubject' : ActorMethod<[bigint], Array<Topic>>,
  'getViewedTopics' : ActorMethod<[], Array<bigint>>,
  'markTopicViewed' : ActorMethod<[bigint], undefined>,
  'searchTopics' : ActorMethod<[string], Array<Topic>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];