/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'keyPoints' : IDL.Vec(IDL.Text),
  'subjectId' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSubject' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addTopic' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getTopic' : IDL.Func([IDL.Nat], [Topic], ['query']),
  'getTopicsBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Topic)], ['query']),
  'getViewedTopics' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'markTopicViewed' : IDL.Func([IDL.Nat], [], []),
  'searchTopics' : IDL.Func([IDL.Text], [IDL.Vec(Topic)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'keyPoints' : IDL.Vec(IDL.Text),
    'subjectId' : IDL.Nat,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addSubject' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addTopic' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getTopic' : IDL.Func([IDL.Nat], [Topic], ['query']),
    'getTopicsBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Topic)], ['query']),
    'getViewedTopics' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'markTopicViewed' : IDL.Func([IDL.Nat], [], []),
    'searchTopics' : IDL.Func([IDL.Text], [IDL.Vec(Topic)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };